package com.paraline.common;

public class GlobalConstants {
    public static final String TITLE_PAGE = "//div[@class ='page-title']/h1";
    public static final String TITLE = "//div[contains(@class, 'fieldset')]//div[1]/strong";
    public static final String TEXT_REMEMBER_ME = ".reversed>label";
    public static final String INPUT_FIRSTNAME = "input#FirstName";
    public static final String INPUT_ADD_FIRSTNAME = "input#Address_FirstName";
    public static final String INPUT_LASTNAME = "input#LastName";
    public static final String INPUT_ADD_LASTNAME = "input#Address_LastName";
    public static final String INPUT_EMAIL = "input#Email";
    public static final String INPUT_ADD_EMAIL = "input#Address_Email";
    public static final String INPUT_COMPANY = "input#Company";
    public static final String INPUT_ADD_COMPANY = "input#Address_Company";
    public static final String INPUT_ADD_CITY = "input#Address_City";
    public static final String INPUT_ADD_ADDRESS1 = "input#Address_Address1";
    public static final String INPUT_ADD_ADDRESS2 = "input#Address_Address2";
    public static final String INPUT_ADD_ZIP = "input#Address_ZipPostalCode";
    public static final String INPUT_ADD_PHONE = "input#Address_PhoneNumber";
    public static final String INPUT_ADD_FAX = "input#Address_FaxNumber";
    public static final String INPUT_PASSWORD = "input#Password";
    public static final String INPUT_OLD_PASSWORD = "input#OldPassword";
    public static final String INPUT_NEW_PASSWORD = "input#NewPassword";
    public static final String INPUT_CONFIRM_PASSWORD = "input#ConfirmPassword";
    public static final String INPUT_CONFIRM_NEW_PASSWORD = "input#ConfirmNewPassword";
    public static final String INPUT_ADD_REVIEW_TITLE = "input#AddProductReview_Title";
    public static final String INPUT_ADD_REVIEW_TEXT = "input#AddProductReview_ReviewText";
    public static final String BUTTON_LOGIN = "//div[@class = 'buttons']/button[contains(@class, 'login')]";
    public static final String EMAIL_ERROR = "#Email-error";
    public static final String CHECK_BOX = "#RememberMe";
    public static final String BTN_NAME = "//div[@class = 'buttons']/button[contains(text(), '%s')]";
    public static final String VALID_ERROR = "//div[contains(@class, 'validation-summary-errors')]";
    public static final String INPUT_GENDER_MALE = "//div[@class = 'form-fields']//div[@class = 'gender']/span[1]";
    public static final String INPUT_GENDER_FEMALE = "//div[@class = 'form-fields']//div[@class = 'gender']/span[2]";
    public static final String SELECT_DATE = "//div[contains(@class, 'date-of-birth')]/div/select[%s]";
    public static final String MESS_SUCCESS = "//div[@class = 'result']";
    public static final String BUTTON_REGISTER = "button##register-button";
    public static final String LIST_BOX = "//div[@class = 'listbox']//li/a[text() = '%s']";
    public static final String BUTTON_ADD = "//div[@class = 'add-button']/button";
    public static final String NOTIFICATION_SUCCESS = "//div[contains(@class,'success')]";
    public static final String SELECT_DATA = "//div[@class = 'inputs']/select[@id = '%s']";
    public static final String INFO = "//div[contains(@class, 'address-item')]//li[@class = '%s']";
    public static final String PRODUCT_REVIEW = "//div[contains(@class, 'product-review')]/a[text() = '%s']";
    public static final String RATING = "//div[@class = 'rating-options']/input[%s]";
    public static final String RESULT = "//div[@class = 'result']";
}
